name: Copy folder to other branch

on: [push]

jobs:
  deploy:
    name: Build Vue Page and deploy to GH-Pages Branch
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Use Node.js
      if: ${{ github.ref == 'refs/heads/master' }}
      uses: actions/setup-node@main
      with:
        node-version: 20.x
    - name: npm install and build
      if: ${{ github.ref == 'refs/heads/master' }}
      run: |
        npm install
        npm run build
    - name: Deploy
      uses: s0/git-publish-subdir-action@develop
      if: ${{ github.ref == 'refs/heads/master' }}
      env:
        REPO: self
        BRANCH: gh-pages
        FOLDER: dist
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
